ref-builder/ref-builder

- ref_builder/index.py
- ref_builder/repo.py
- ref_builder/snapshotter/snapshotter.py
- tests/snapshotter/test_snapshotter.py
- tests/test_add.py
- tests/test_repo.py
* Remove the `Repo.get_all_otus()` method.
* Bring `ignore_cache` ability into `iter_otus`.
* Move all `get_all_otus` usages to `iter_otus`.
> refactor: remove `get_all_otus`

- ref_builder/cli.py
- ref_builder/console.py
- ref_builder/legacy/repo.py
- ref_builder/legacy/utils.py
- ref_builder/legacy/validate.py
- ref_builder/repo.py
- ref_builder/snapshotter/snapshotter.py
- ref_builder/utils.py
- tests/ncbi/test_ncbi_client.py
* Add commands to list OTUs and show details of a single OTU.
* Clean up CLI module, resolving most Ruff linter errors.
* Remove flaky mark from NCBI tests. The package is not installed and we should be ensuring these tests always pass by making the code more resilient.
* Remove unused `async` from NCBI tests.
* Remove some log calls. We need to rethink this so it doesn't clutter the output. One idea is logging to stderr or writing log files.
Output of `ref-builder otu list`:
```text
NAME                    ACRONYM  ID                                    TAXID
Abaca bunchy top virus  ABTV     586ba010-4121-48a5-bf0c-f4462cc07b0c  438782
Abutilon Brazil virus   AbBV     12e98766-2870-4334-a9cd-1705fd8d2066  665102
```
Output of `ref-builder otu get`:
```text
Abaca bunchy top virus
ACRONYM …
```
> Add commands for showing OTU data

- ref_builder/events.py
- ref_builder/otu.py
- ref_builder/repo.py
- ref_builder/resources.py
- tests/__snapshots__/test_add.ambr
- tests/test_add.py
- tests/test_repo.py
* Add `SetReprIsolate` event
* Add `test_otu_model_adherence` to monitor missing fields in `OTUSnapshotOTU`
* Add `.repr_isolate` and `.excluded_accessions` fields to OTU snapshots
* Fix missing taxid existence check in `create_otu_with_schema()`
> Add SetReprIsolate

- ref_builder/cli.py
- ref_builder/otu.py
- ref_builder/repo.py
- tests/__snapshots__/test_add.ambr
- tests/test_add.py
- add: `ref-builder otu update [TAXID] isolate [ACCESSIONS]`
- rename: `ref-builder otu update` -> `ref-builder otu update [TAXID] autoupdate`
- remove: `ref-builder sequences create`
- rename: `update_otu()` -> `auto_update_otu()`
- add: `create_isolate()` as new default isolate creation function for both `add_isolate()` and `auto_update_otu()`
- chore: `TestUpdateOTU` now uses `2164102` as test case
> ECO-73: Replace individual sequence addition with isolate addition

- ref_builder/otu/create.py
- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- tests/__snapshots__/test_add.ambr
`create_otu()` and `create_isolate_from_records()` identify RefSeq records, parse the comment for superceded accessions and automatically add them to the excluded accessions for that OTU.
Partially handles ECO-77. Automatic deletion of existing sequences will be added once deletion events are merged.
> feat: automatically exclude pre-RefSeq accessions (ECO-77)

- pyproject.toml
This is annoying and resolving it makes the code unnecessarily verbose.
> chore: ignore EM102 about f-strings in exceptions

- ref_builder/otu/create.py
- ref_builder/otu/update.py
- ref_builder/repo.py
- tests/test_repo.py
* Take `IsolateName` instead of source_type and source_name.
* Raise a `ValueError` instead of returning `None` when the isolate name already exists. This makes the method consistent with `create_otu`.
* Add a test for the name clash error.
> Refactor `Repo.create_isolate`

- ref_builder/otu/update.py
- tests/__snapshots__/test_add.ambr
- tests/test_add.py
* move isolate/sequence creation from of `update_otu_with_accessions()` into `file_records_into_otu()` 
* add `_bin_refseq_records()` utility function
* `update_otu_with_accessions()` divides `records` into RefSeq and non-RefSeq lists and calls `file_records_into_otu()` for each automatically
> fix: `update_otu_with_accessions()` adds RefSeq isolates correctly

- ref_builder/cli.py
- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- tests/__snapshots__/test_add.ambr
- tests/test_add.py
- tests/test_modify.py
* add `otu.update.delete_isolate_from_otu()`, `.update_isolate_from_records()`, `.update_isolate_from_accessions()`
* add `otu.utils.DeleteRationale` enum
* add `otu.utils.RefSeqConflictError` to handle `add_isolate()` cases where an automatic RefSeq promotion is likely possible
> ECO-77: Add isolate sequence replacement functions

- ref_builder/repo.py
- ref_builder/resources.py
- ref_builder/snapshotter/otu.py
- tests/__snapshots__/test_add.ambr
- tests/snapshotter/test_models.py
- tests/snapshotter/test_otu.py
- tests/test_repo.py
- tests/test_resources.py
Convert `RepoSequence`, `RepoIsolate`, `RepoOTU` to Pydantic models.
Having these as custom classes or dataclasses is causing problems for cleanly serializing their data.
> Use Pydantic for more resources

- ref_builder/cli.py
- ref_builder/otu/update.py
- tests/test_add.py
- tests/test_modify.py
* split `add_isolate()` into `add_genbank_isolate()`, `add_unnamed_isolate()`, `add_and_name_isolate()`
* add `otu.update._create_fetch_list()` utility function
* add `--unnamed` flag to `add-isolate`
* add `--name ISOLATE_TYPE ISOLATE_NAME` option, defaults to `(None, None)`
> ECO-60: add override flag to `add isolate`

- ref_builder/ncbi/client.py
- ref_builder/otu/utils.py
- ref_builder/schema.py
- tests/__snapshots__/test_add.ambr
- tests/ref/test_schema.py
Formats all multipartite segment names to `[PREFIX] [KEY]` where possible. Handles dashes, underscores and missing prefixes.
* add: `schema.SegmentName`
* add: `schema.get_multipartite_segment_name()`
* add: `schema.determine_segment_prefix()`
* add `TestSegmentNameParser`
> ECO-64: Handle segment name ambiguity

- ref_builder/cli.py
- ref_builder/console.py
- ref_builder/options.py
- ref_builder/otu/create.py
- tests/__snapshots__/test_add.ambr
- tests/test_add.py
The main drive for this PR is resolving Ruff format and linter warnings.
* Move `--debug` option and logging configuration to root command.
* Remove `--autofill` option from `otu create`. This should be done by a subsequent `otu update automatic`.
* Fixing typing issues.
* Update command docs.
* Extract legacy repo path option to `options.py`.
> Update CLI module

- .github/workflows/ci.yml
- pyproject.toml
* Stop running `commitlint`. This is ignored and PRs are rebased in practice.
* Run `ruff format --check` to ensure only correctly formatted code is merged.
> ci: drop commitlint and add ruff format check

- pyproject.toml
- ref_builder/cli/main.py
- ref_builder/cli/validate.py
- ref_builder/otu/update.py
- tests/test_add.py
* Return error when duplicate accessions are provided for OTU or isolate creation.
* Discount duplicate accession during accesssion exclusion. Only the first occurence will be excluded.
* Update docs accordingly.
> feat: return error when duplicate accessions provided

- ref_builder/ncbi/client.py
* Make sure accessions are properly paged through.
The previous commit related to this was totally incorrect.
> fix: fetch all accessions associated with a taxonomy id

- ref_builder/cli/main.py
- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- ref_builder/plan.py
- ref_builder/repo.py
- ref_builder/resources.py
- tests/__snapshots__/test_add.ambr
- tests/__snapshots__/test_modify.ambr
- tests/ref/__snapshots__/test_schema.ambr
- tests/ref/test_schema.py
- tests/test_modify.py
- tests/test_repo.py
- tests/test_resources.py
* add `ref-builder otu update TAXID plan extend [ACCESSIONS] --optional`
* add `ref-builder otu update TAXID plan multipartite  --name [prefix, key] --optional [ACCESSIONS]`
* add `otu.update.set_isolate_plan()` to directly access replacement
* allow `Segment.name = None`
> ECO-92: add isolate plan modification commands

- ref_builder/ncbi/client.py
- ref_builder/otu/update.py
- tests/__snapshots__/test_add.ambr
- tests/__snapshots__/test_update.ambr
- tests/test_add.py
- tests/test_update.py
* `test_add::TestUpdate` moved to new `test_update` to isolate its heavier server dependency
* update accession lists in `TestUpdate` for new accessions
* clean up logging in `NCBIClient.fetch_genbank_records()`
> update tests; improve logging in `ncbi.client`, `otu.update`

- ref_builder/cli/main.py
- ref_builder/otu/modify.py
- ref_builder/otu/update.py
- tests/test_modify.py
* `ref-builder otu update TAXID`: invoke help dialog if no subcommand is given
* move OTU plan modification functions from `otu.update.*` to `otu.modify.*`
> automatic help dialog for `ref-builder otu update TAXID`

- ref_builder/cli/main.py
- ref_builder/logs.py
- tests/conftest.py
* Only show logging above `WARNING` when `-v`, `-vv`, or `--debug` are set.
* Focus on `structlog` features in configuration, minimizing use of `logging`.
The idea with this is to progressively use `rich` to render the results of operations. Logging
should be focused on output for development troubleshooting.
> Revise logging

- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- tests/__snapshots__/test_console.ambr
- tests/fixtures/providers.py
- tests/ref/test_inclusion_checks.py
- tests/ref/test_utils.py
* feat: reject monopartite sequences that fall outside of the mandated length tolerance
* add `otu.utils.check_sequence_length()`
* add `test_inclusion_checks`
> ECO-95 (partial): Reject new monopartite sequences with invalid lengths

- ref_builder/ncbi/client.py
- ref_builder/otu/utils.py
* change `accessions` argument typing in `NCBIClient.fetch_genbank_records()`, `.fetch_unvalidated_genbank_records()` from `list` to `Collection`
* implement set-friendly fetch in `otu.utils.fetch_records_from_accessions()`
> chore: allow any `Collection` as NCBI fetch argument

- ref_builder/repo.py
- tests/test_repo.py
* add `TestExcludeAccessions.test_fail()`
* remove `test_exclude_accession()`
> fix: `Repo.exclude_accessions()` omits `OTU.accessions` contents

- ref_builder/ncbi/client.py
- tests/ncbi/test_client.py
* address infinite loop bug in `NCBIClient.fetch_accessions_by_taxid()` (bug took place because `result["Count"]` returns total count, not page count)
* add corresponding test
> fix: `NCBIClient.fetch_accessions_by_taxid()` infinite loop

- ref_builder/plan.py
- tests/test_add.py
- tests/test_plan.py
* Parse segment names without delimiters using plan when creating a new OTU
> fix: delimiter-less segments don't `break create_otu()`

- ref_builder/cli/otu.py
- tests/cli/test_print_commands.py
- tests/conftest.py
* fix `scratch_event_store_data` return bug
* add CLI tests for `ref-builder otu list` and `ref-builder otu get`
> fix: missing `as_json` arg in `otu_get`

- ref_builder/otu/utils.py
* Always try to get segment names from plans or parsing before using moltype.
* Parse segment names without delimiters using plans.
* Parse segment names without prefixes using plans.
> fix: repair renamed function call

- ref_builder/legacy/convert.py
- ref_builder/otu/utils.py
- ref_builder/plan.py
- tests/test_plan.py
* Always try to get segment names from plans or parsing before using moltype.
* Parse segment names without delimiters using plans.
* Parse segment names without prefixes using plans.
* Resolves ECO-116.
* Resolves ECO-117.
> fix: handle incomplete and delimiter-less genbank segment names

- ref_builder/resources.py
- tests/fixtures/factories.py
- tests/test_resources.py
Addresses a bug where `RepoOTU.add_isolate()` does not add new sequences to `._sequences_by_id`, thereby causing a `KeyError` during `RepoOTU.delete_isolate()`.
* fix: ensure `RepoOTU.add_isolate()` adds the new sequence IDs to its private index
* add tests ensuring RepoIsolate sequences are accounted for in RepoOTU private index
* refactor: raise specific `ValueError` in `RepoOTU.delete_isolate()` if a key is not found 
* add test for `RepoOTU.delete_isolate()`
* delete unused `RepoIsolate.replace_sequence()`, `RepoOTU.replace_sequence()`
Resolves ECO-129
> fix `RepoOTU._sequences_by_id` bugs

- ref_builder/cli/otu.py
- ref_builder/repo.py
- tests/test_add.py
* refactor `RepoOTU.create_otu()`: log the OTU ID of a conflicting OTU, rather than the entire `RepoOTU` contents
* check console output in `TestCreateOTUCommands.test_ok()`
* move `TestCreateOTUCommands.test_duplicate_accessions()`
> REF-3: Print new OTU after creation

- ref_builder/plan.py
* if plan given to `extract_segment_name_from_record_with_plan()` is monopartite, return `None` rather than attempting to build a `plan_keys_and_prefixes` table
> fix: segment extraction with monopartite plan `AttributeError`

- ref_builder/cli/isolate.py
- ref_builder/otu/isolate.py
- tests/cli/test_isolate_commands.py
- tests/test_add.py
This PR restores lost `ref-builder isolate create` command functionality and updates test coverage to match.
* add `test_isolate_commands::TestIsolateCreateCommand` to check `isolate create` commands run as expected
* fix: midway created isolate aborts the transaction
* fix: remove overly nested transactions from CLI code
* fix: successful `ref-builder create isolate` no longer exits with exit code 1
> fix: `ref-builder isolate create [ACCESSIONS]`

- ref_builder/cli/otu.py
- ref_builder/otu/modify.py
- ref_builder/repo.py
- tests/cli/__snapshots__/test_otu_commands.ambr
- tests/cli/test_otu_commands.py
- tests/test_add.py
Restores lost CLI access to two commands.
* allow use of OTU id (full or partial) as identifier
* move `TestCreateOTUCommands` to `tests.cli.test_otu_commands`
> fix: `otu exclude-accessions`, `otu allow-accessions`

- ref_builder/cli/otu.py
- ref_builder/otu/update.py
* after running `batch_fetch_new_accessions()`, save the resulting fetch index of new accessions to `.cache`
* add `--fetch-index-path PATH`, allowing the user to input a previously saved fetch-index
* add `--precache`, `--precache-batch-size` to control whether all records are precached before adding to repo and how many records should be fetched at once.
> feat: add `otu batch-update` convenience options

- ref_builder/otu/update.py
Removes crashes caused by improper use of `structlog` `.exception()`
> fix: address `logger.exception()` related crashes

- ref_builder/cli/isolate.py
- ref_builder/otu/modify.py
- ref_builder/repo.py
- tests/cli/test_isolate_commands.py
- tests/cli/test_otu_commands.py
- tests/test_modify.py
- tests/test_repo.py
* add `TestDeleteIsolate` to `test_repo`
* chore: remove duplicate `otu promote` test
* chore: mark `TestPromoteOTUCommand` as NCBI-dependent
> disallow deletion of an OTU's representative isolate

- ref_builder/repo.py
- ref_builder/utils.py
- tests/test_repo.py
* update `Repo.exclude_accession()` to match `.exclude_accessions()`
* better logs
* more readable tests
> improve `Repo.exclude_accessions()` and associated tests

- ref_builder/otu/update.py
- fix: `update_otu_with_records()` no longer ignores RefSeq records during the isolate addition step
- fix: `batch_update_repo()` skips concatenation of fetch set when `precache = False` 
- add: `PrecachedRecordStore` and `BatchRecordFetcher` classes, derived from abstract base class `BaseBatchRecordGetter`
- refactor: consolidate `if precache` split in `batch_update_repo()` using  `BaseBatchRecordGetter` children
- remove: `_bin_refseq_records()`
> improvements to `otu update` and `otu batch-update`

- tests/ncbi/__snapshots__/test_client.ambr
- tests/ncbi/test_client.py
* NCBI Taxonomy now [ranks "Viruses" as "acellular root"](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=10239&lvl=3&lin=f&keep=1&srchmode=1&unlock)
* snapshot dumped model for readability
> fix: account for NCBI Taxonomy lineage change

- ref_builder/plan.py
- ref_builder/resources.py
- tests/test_resources.py
Add `RepoOTU.check_plan_required()` field validator.
> REF-5: Warn about no required segments when creating OTUs

- ref_builder/cli/otu.py
- ref_builder/otu/modify.py
- ref_builder/otu/promote.py
- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- ref_builder/plan.py
- ref_builder/repo.py
- ref_builder/resources.py
- tests/cli/test_otu_commands.py
- tests/test_modify.py
- tests/test_promote.py
- tests/test_repo.py
- tests/test_resources.py
- tests/test_update.py
Refactor sequence promotion and replacement so that sequences linked to multiple isolates can be replaced without issue.
Resolves REF-38.
* refactor `Repo.replace_sequence()` so that the `DeleteSequence` event is conditional on sequence existence  
* add `RepoOTU.get_isolate_ids_containing_sequence_id()`
* deprecate `RepoOTU.get_sequence_id_hierarchy_from_accession()`
* create `otu.promote` submodule
* refactor `otu.promote_otu_accessions_from_records()`
* refactor `otu.modify.replace_sequence_in_otu()`
* add `test_promote`
> fix REF-38: refactor `promote_otu_accessions_from_records()`

- ref_builder/otu/models.py
- ref_builder/otu/validate.py
- ref_builder/repo.py
- tests/otu/test_models.py
- tests/otu/test_validation.py
- tests/test_repo.py
- tests/test_transaction.py
- tests/test_update.py
Follow-up to suggestions in [PR-135](https://github.com/virtool/ref-builder/pull/135).
* add `otu.validate.check_otu_is_valid()`
* `Repo.use_transaction()`: after transaction actions are complete, iterate through event queries to find affected OTU ids. If `check_otu_is_valid()` returns false on any affected OTUs, raise `AbortTransactionError`.
* knock-on changes to `test_repo`, `test_transactions`
* `OTUBase`: replace `.sequences` field with property
> REF-40: Automatically validate OTU before transaction is committed

- ref_builder/repo.py
- ref_builder/resources.py
- tests/fixtures/factories.py
Fixes invalid `SegmentFactory.build()` in `PlanFactory`.
* `Repo._rehydrate_otu()`: catch and record warnings for logging
* make `._rehydrate_otu()` into `staticmethod`
> fix: bad `PlanFactory` segments, unhelpful console output

- ref_builder/cli/otu.py
- ref_builder/otu/modify.py
- ref_builder/plan.py
- tests/__snapshots__/test_modify.ambr
- tests/test_modify.py
* refactor: `add_segments_to_plan()` now returns `{UUID}` instead of `Plan | None`
* fix: `ref-builder otu extend-plan` no longer creates a nested transaction
* chore: `add_segments_to_plan()`: if not all requested segments can be created, return an empty set
* chore: deprecate `otu.modify.resize_monopartite_plan()`
* add `Plan.segment_ids` convenience property
> refactor: `add_segments_to_plan()`

- ref_builder/otu/isolate.py
- ref_builder/otu/models.py
- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- ref_builder/otu/validate.py
- ref_builder/repo.py
- ref_builder/resources.py
- ref_builder/utils.py
- tests/otu/test_models.py
- tests/ref/test_inclusion_checks.py
- tests/test_add.py
- tests/test_promote.py
- tests/test_repo.py
- tests/test_resources.py
Offload some function-dependent validation onto the `OTU` validator model for more consistent results across different functions. 
Resolves GH-147 and GH-149.
* add `Sequence.check_accession_key_is_valid()` field validator
* add `Isolate.check_accession_consistency()` field validator
* add `OTU.check_isolates_against_plan()` model validator
* add `OTU.check_plan_required()` field validator (removed from `RepoOTU`)
* add `PlanConformationError`
* add `IsolateInconsistencyWarning`
* add `otu.validators.otu_error_handler()`
> Use `OTU` validation to replace some checks

- ref_builder/index.py
Utilize [adapters](https://docs.python.org/3/library/sqlite3.html#how-to-adapt-custom-python-types-to-sqlite-values) and [converters](https://docs.python.org/3/library/sqlite3.html#how-to-convert-sqlite-values-to-custom-python-types) to cut down on inline type casting and conversion when dealing with SQLite data.
* add `index.adapt_uuid()`/`.convert_uuid()`, `.adapt_datetime()`/ `.convert_uuid()`
> refactor `Index` methods using type adapters and converters

- ref_builder/cli/otu.py
- ref_builder/ncbi/cache.py
- ref_builder/ncbi/client.py
- ref_builder/otu/builders/isolate.py
- ref_builder/otu/builders/otu.py
- ref_builder/otu/promote.py
- ref_builder/repo.py
- tests/cli/test_otu_commands.py
- tests/test_promote.py
Add a new OTU command to upgrade sequences that have undergone modification in NCBI Nucleotide since last added.
Resolves GH-148.
* add `OTUBuilder.versioned_accessions` property
* refactor `Repo.create_sequence()`, `otu.promote.replace_otu_sequence_from_record()` to use `OTU.versioned_accessions` to check for sequence clash
* refactor `NCBIClient.fetch_genbank_records()` to take accession version into account when retrieving from cache
* add `otu.promote_otu_accessions_from_records()`
* add `test_promote::TestUpgradeSequencesInOTU`, `test_otu_commands::TestUpgradeOTUCommand`
> add `ref-builder otu upgrade IDENTIFIER`

- ref_builder/ncbi/client.py
- ref_builder/ncbi/models.py
- tests/ncbi/test_client.py
Allows `NCBITaxonomy` to handle taxonomical rank issues using internal validator.
* add `client.TaxonLevelError`
* add rank validators to `NCBITaxonomy`
* add some higher-level ranks to `NCBIRank` for convenience
* clean up `NCBIClient.fetch_accessions_by_taxid()`
* add `TestFetchTaxonomy.test_rank_too_high_fail()`
> improvements to `NCBIClient.fetch_taxonomy()`, etc.

- ref_builder/cli/main.py
- ref_builder/logs.py
- tests/cli/test_entry_command.py
- tests/cli/test_otu_commands.py
Comply with suggested [NO_COLOR](https://no-color.org/) standards. Makes for cleaner exported logfiles.
So, `ref-builder --no-color otu create [ACCESSIONS]` will use the structlog JSON processor. The presence of a `NO_COLOR` environment variable will also disable coloured output.
> add `--no-color` option to top-level command

- ref_builder/cli/utils.py
- ref_builder/index.py
- ref_builder/repo.py
- tests/cli/test_print_commands.py
- tests/conftest.py
- tests/test_index.py
- tests/test_repo.py
Add retrieve-by-acronym functionality to `cli.utils.get_otu_by_identifier()`
e.g. `ref-builder otu get ABTV` should return the data for Abaca bunchy top virus.
* add `Index.get_id_by_acronym()`
* add `Repo.get_otu_id_by_acronym()`
> feat: add access to indexed OTUs by acronym 

- ref_builder/legacy/convert.py
- ref_builder/otu/models.py
- ref_builder/otu/promote.py
- ref_builder/otu/utils.py
- ref_builder/otu/validators/otu.py
Resolves an issue where `legacy.convert_legacy_repo()` occasionally created plan segments 1 character too tight (main fix in [ab549f0](https://github.com/ref-builder/ref-builder/pull/167/commits/ab547f0617e24fb965348ee429a5ec7ea9369880)).
* fix: handle a failed sequence promotion inside `otu.promote.promote_otu_accessions_from_records()` without tripping `AttributeError`
* fix: set `LegacyId` minimum length to 1, as legacy isolate ids can be very short
> fix: segment length rounding errors

- ref_builder/repo.py
- tests/test_repo.py
* rename `Repo._prune()` -> `._prune_events()`
> fix: `Repo` not pruning `Repo._index` tables on initialization

- ref_builder/plan.py
- tests/test_plan.py
Resolves a bug where `plan.extract_segment_name_from_record()` parsed undelimited strings differently from `.extract_segment_name_from_record()`, thus causing false negative matches in the latter.
* add `plan.UNDELIMITED_NAME_PATTERN`
* use regex to handle undelimited name pattern inside `Segment.from_string()`
* disallow whitespace characters in `plan.COMPLEX_NAME_PATTERN` key group
* add undelimited case to `test_plan::TestSegmentName.test_from_string()`
> fix: inconsistent segment name extraction

- ref_builder/cli/utils.py
- ref_builder/errors.py
- ref_builder/events/otu.py
- ref_builder/index.py
- ref_builder/repo.py
- ref_builder/store.py
- ref_builder/utils.py
- tests/cli/test_otu_commands.py
- tests/cli/test_print_commands.py
- tests/ncbi/__snapshots__/test_client.ambr
- tests/test_add.py
- tests/test_repo.py
Allows for the removal of an OTU from repo iteration and indexes.
Event records remain in the `events` table for posterity.
* add `DeleteOTU` event
* add `errors.OTUDeletedError`
* add `test_repo::TestDeleteOTU`
> feat: add `DeleteOTU` event
