- ref_builder/repo.py
* Always cache snapshot when `get_otu` is called.
* Instead of building `RepoOTU` in methods where events are created, call `get_otu` to generate the return value. This also ensures that we have only one place that valid `RepoOTU` instances are built.
* Improve a bunch docstrings and typing.
> refactor: simplify snapshot trigger

- ref_builder/otu.py
- ref_builder/snapshotter/otu.py
- tests/snapshotter/test_models.py
* fix: `create_otu_with_schema()` checks `taxid` existence before proceeding
* add `test_otu_model_adherence` to snapshot model tests
> add `.excluded_accessions` to OTU snapshots

- ref_builder/legacy/utils.py
- ref_builder/legacy/validate.py
Addresses incompatibility issues on platforms that automatically create OS-specific metadata files.
> fix: legacy iterators ignore invalid files

- ref_builder/events.py
- ref_builder/repo.py
- ref_builder/resources.py
- tests/test_repo.py
- tests/test_resources.py
* add `Repo.delete_isolate()` and `.replace_sequence()`
* add `RepoIsolate.replace_sequence()` and `.delete_sequence()`
* add `RepoOTU.delete_isolate()`, `.replace_sequence` and `.delete_sequence()`
* add new utility functions to `RepoOTU` and `RepoIsolate`
> add: isolate and sequence redaction

- ref_builder/cli.py
- ref_builder/otu/update.py
- ref_builder/repo.py
* add `otu update TAXID exclude ACCESSIONS` command
> feat: add accessions to an OTU's excluded accession list from CLI

- ref_builder/ncbi/client.py
- ref_builder/otu/utils.py
- ref_builder/repo.py
- ref_builder/resources.py
- ref_builder/snapshotter/models.py
- ref_builder/utils.py
- tests/ncbi/test_cache.py
* Change `create_from_string` to `from_string` to follow convention.
* Add documentation.
> Rename `Accession` classmethod

- ref_builder/snapshotter/snapshotter.py
- tests/snapshotter/test_snapshotter.py
* Add or improve documentation and typing.
* Remove unused methods and properties.
> refactor: cleanup snapshotter

- ref_builder/repo.py
- ref_builder/snapshotter/snapshotter.py
This better supports any changes to the backing implementation.
> refactor: change direct snapshotter access to get methods

- ref_builder/cli.py
- ref_builder/otu/update.py
- tests/test_modify.py
Breaks off from original content of #25.
* add `.set_representative_isolate()`
* add `otu update TAXID representative ISOLATE_ID` command
* add `test_modify`
> feat: update representative isolate

- ref_builder/otu/utils.py
- ref_builder/schema.py
- tests/__snapshots__/test_add.ambr
- tests/ref/__snapshots__/test_schema.ambr
- tests/ref/test_schema.py
- tests/snapshotter/__snapshots__/test_models.ambr
- tests/test_add.py
- tests/test_repo.py
- tests/test_resources.py
* add `Segment.id` field to all schemas
* fix expected snapshotter test output
> ECO-76: add UUID `id` to `Segment`

- ref_builder/ncbi/cache.py
- ref_builder/ncbi/client.py
- ref_builder/ncbi/models.py
Prepare for merging `ruff` CI step.
* Apply `ruff` formatting.
* Accept and apply `ruff` linter suggestions.
> refactor: format and clean up ncbi module

- ref_builder/events/repo.py
- ref_builder/repo.py
- ref_builder/resources.py
- tests/test_repo.py
* add `resources.RepoSettings`
* add `default_segment_length_tolerance` arg to `Repo.new()`
* add `.settings` field to `CreateRepo`
* expand `test_repo.test_new` into `TestNew`
> ECO-98: add `RepoSettings`

- ref_builder/otu/create.py
- ref_builder/otu/modify.py
- ref_builder/otu/utils.py
- ref_builder/plan.py
- tests/__snapshots__/test_add.ambr
- tests/__snapshots__/test_modify.ambr
- tests/ref/__snapshots__/test_schema.ambr
- tests/ref/test_schema.py
- tests/test_add.py
- tests/test_modify.py
- tests/test_repo.py
- tests/test_resources.py
* add `.length_tolerance` to `Segment` and `MonopartitePlan`
* add `otu.modify.set_plan_length_tolerances()`
* add `TestSetIsolatePlan.test_set_length_tolerances()`
> ECO-100: add `.length_tolerance` to `Segment` and `MonopartitePlan`

- ref_builder/otu/models.py
- ref_builder/resources.py
- tests/fixtures/factories.py
- tests/otu/test_models.py
- tests/test_repo.py
- tests/test_resources.py
* Remove `RepoOTU.sequence_ids` that was used only in test.
* Add polyfactory that creates complete, validated OTUs.
* Add base and validation classes for OTUs. These have not been used yet.
> Validation classes

- ref_builder/otu/utils.py
- ref_builder/plan.py
- tests/fixtures/factories.py
- tests/otu/test_prevalidation.py
* add `otu.utils.assign_records_to_segments()`
* add `TestAssignRecordsToSegments`
* add `MultipartitePlan.secondary_segments`
* add `NCBIGenbankFactory.build_from_metadata()` mock record generator
> add record segment classification utility

- poetry.lock
- ref_builder/build.py
- ref_builder/events/otu.py
- ref_builder/otu/create.py
- ref_builder/otu/models.py
- ref_builder/otu/modify.py
- ref_builder/repo.py
- ref_builder/resources.py
- tests/fixtures/factories.py
- tests/otu/test_models.py
- tests/test_add.py
- tests/test_console.py
- tests/test_modify.py
- tests/test_repo.py
- tests/test_resources.py
- tests/test_update.py
* Rename event.
* Rename field on models.
* Rename variables that refer to representative isolate values.
> feat: rename `SetReprIsolate` to `SetRepresentativeIsolate`

- ref_builder/otu/modify.py
- tests/test_modify.py
* refactor `otu.modify.exclude_accessions_from_otu()`
* add `otu.modify.allow_accessions_into_otu()`
* add test for the above
> Streamline OTU accession exclusion functions

- ref_builder/cli/otu.py
- ref_builder/otu/update.py
Resolves ECO-199
* adds `ignore_cache` option to auto update
> fix: `otu update` options

- ref_builder/console.py
- ref_builder/index.py
- tests/__snapshots__/test_console.ambr
- tests/test_console.py
* Improve SQLite query with `fetchall` instead of iteration through cursor.
* Improve console printing by ditching Rich.
> Improve `otu list` performance

- ref_builder/resources.py
* remove buggy lookup tables from `RepoIsolate`
* fix `RepoIsolate.get_sequence_by_id()` bug
* Resolves ECO-110
> fix `RepoIsolate` sequence key error

- ref_builder/index.py
- ref_builder/repo.py
- tests/test_index.py
- tests/test_repo.py
* add `Repo.get_otu_id_by_isolate_id()`
* add `Repo.get_isolate_id_by_partial()`
> ECO-128: add `isolates` table to `index.db`

- ref_builder/cli/event.py
- ref_builder/cli/events.py
- ref_builder/cli/main.py
- ref_builder/cli/otu.py
- ref_builder/console.py
- ref_builder/events/base.py
- ref_builder/index.py
- ref_builder/repo.py
- tests/cli/test_event_commands.py
- tests/ref/test_event_log.py
* add `ref-builder event list` and `--otu IDENTIFIER` variation
* add `ref-builder events get EVENT_ID`
> add `event list`  and `event get` commands

- ref_builder/otu/isolate.py
- ref_builder/repo.py
- ref_builder/transaction.py
> chore: clean up `Transaction` usage

- pyproject.toml
- ref_builder/otu/create.py
- ref_builder/otu/isolate.py
- ref_builder/otu/models.py
- ref_builder/otu/modify.py
- ref_builder/otu/update.py
- ref_builder/otu/utils.py
- ref_builder/otu/validators/isolate.py
- ref_builder/otu/validators/otu.py
- ref_builder/otu/validators/sequence.py
- ref_builder/repo.py
- ref_builder/utils.py
- tests/__snapshots__/test_add.ambr
- tests/conftest.py
- tests/test_add.py
- tests/test_repo.py
* use `OTUFactory` to generate data for `indexable_otus` fixture
* add `otu.models.LegacyId` annotated type
* add some Field checks
* clean up some missing docstrings and type hints
> Improvements to OTU validation

- .github/CODEOWNERS
- .github/dependabot.yaml
- **ci: add dependabot configuration**
- **ci: remove CODEOWNERS**
> Configure Dependabot and CODEOWNERS
